name: Main workflow

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-dev-container:
    name: Build development container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: |
          docker build -t ghcr.io/NAMESPACE/workshop-ci:latest -f Dockerfile .
      - name: Push container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u NAMESPACE --password-stdin
          docker push ghcr.io/NAMESPACE/workshop-ci:latest
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    needs: build-dev-container
    container:
      image: ghcr.io/NAMESPACE/workshop-ci:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        run: |
          composer phpcs-ci