name: Main workflow

on:
  pull_request:
  push:

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        run: |
          docker run -it \
          -v $(pwd)/src:/code/app \
          registry.gitlab.com/pipeline-components/php-codesniffer:latest \
          phpcs -s -p --extensions=php --standard=PSR1,PSR2,PSR12 app
        
